spring:
  application:
    name: coupons
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration